INSERT INTO users(userName, mailAddress, password, role) VALUES('userName3', 'mailaddress3@gmail.co.jp', '$2a$10$xRTXvpMWly0oGiu65WZlm.3YL95LGVV2ASFjDhe6WF4.Qji1huIPa', 'ROLE_GENERAL') ON CONFLICT DO NOTHING;
INSERT INTO users(userName, mailAddress, password, role) VALUES('userName4', 'mailaddress3@gmail.co.jp', '$2a$10$xRTXvpMWly0oGiu65WZlm.3YL95LGVV2ASFjDhe6WF4.Qji1huIPa', 'ROLE_GENERAL') ON CONFLICT DO NOTHING;
INSERT INTO users(userName, mailAddress, password, role, isEnabled) VALUES('disabledUser', 'mailaddress3@gmail.co.jp', '$2a$10$xRTXvpMWly0oGiu65WZlm.3YL95LGVV2ASFjDhe6WF4.Qji1huIPa', 'ROLE_GENERAL', 'false') ON CONFLICT DO NOTHING;
INSERT INTO users(userName, mailAddress, password, role) VALUES('userName6', 'mailaddress3@gmail.co.jp', '$2a$10$xRTXvpMWly0oGiu65WZlm.3YL95LGVV2ASFjDhe6WF4.Qji1huIPa', 'ROLE_GENERAL') ON CONFLICT DO NOTHING;

INSERT INTO recommenders(recommenderName) VALUES('中越典子') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('ミムラ') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('掛布雅之') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('石井慧') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('浅田真央') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('伊東美咲') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('宮沢りえ') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('おぎやはぎ') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('太田雄貴') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('上田桃子') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('高橋克実＆八嶋智人') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('小倉優子') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('宮里藍') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('加藤ローサ') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('美川憲一') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('水川あさみ') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('綾小路きみまろ') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('大泉洋') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('ウエンツ瑛士') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('ガレッジセール') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('奥菜恵') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('倉本聰') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('白石美帆') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('磯野貴理子') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('綾戸智恵') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('貫地谷しほり') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('長澤まさみ') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('秋吉久美子') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('上村愛子') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('中居正広') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName) VALUES('石井一久') ON CONFLICT DO NOTHING;
INSERT INTO recommenders(recommenderName, isEnabled) VALUES('無効リコメンダー', 'false') ON CONFLICT DO NOTHING;

INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1000', 'マカロン', '120個入　3938円', '1000.jpg', 'ショコラアメール/ショコラヴァニーユ/ショコラフランボワーズショコラキャラメル/ショコラカフェ/ショコラミエルショコラピスターシュ/ショコラベルガモット/ショコラパッションポムアニス/マングコリアンドル/パンオレザン上記、12種類', 'ジャン＝ポール･エヴァン伊勢丹新宿店', '東京都新宿区新宿3-14-1伊勢丹新宿店本館B1階', '03-3352-1111') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1001', '五家寶', '細巻6本入り 170円', '1001.jpg', '各種詰め合わせあります。ぷうん、と香るきな粉の香ばしさ、サクッとした歯応え、そしてすうっと溶け入る舌触り・・・・・・。主原料である大豆、糯米、砂糖、水飴等が織りなすこの豊かな風味は、総て独自のものを用い、心のこもった手造りによる『花堤五家寳』ならではのものです。', '花堤', '玉県熊谷市榎町3', '048-521-0471') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1002', 'ロールケーキ', '1000円', '1002.jpg', 'ロールケーキ専門店で、手作りしている為、1日80本限定販売です。平飼地鶏の有精自然卵、国内産の小麦粉、砂糖、低脂肪の純生クリームと厳選された素材を使用しています。もちろん、添加物、保存料は一切使用していません。このロールケーキはプレーンとチョコの２種類で、カフェでは、ロールケーキと飲み物のセットがあります。', 'Flat', '豊中市上野東3-18-8', '06-6848-7505') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1003', 'ピロシキ', '1個　120円', '1003.jpg', '', '木村屋', '大阪府大阪市天王寺区石ケ辻町13-20', '06-6771-4107') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1004', 'いちご大福', '1箱10個入　1900円', '1004.jpg', '11月中旬4月下旬限定白餡を羽二重餅で包み、みずみずしいイチゴを丸ごとサンドしました。', '御菓子司福岡屋', '愛知県豊田市保見町塚原15', '056-548-8036') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1005', 'フロマージュロワイヤル', '1箱　2100円 ', '1005.jpg', '★数量限定発売★有名パティシエ高木康政の濃厚チーズケーキ【フロマージュロワイヤル】３ヶ国の厳選したチーズと、タカギオリジナルの製法で焼き上げた濃厚なチーズケーキです。ずっしりとした重量感があるのに食べてみると、ちーずの芳醇な香りとまろやかな口当たりでしつこさを感じさせません。一度食べるとやめられないタカギで大人気のケーキです。', 'ルパティシエタカギ', '東京都世田谷区深沢5-5-21', '03-5420-2929') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1006', 'だだちゃ・アイスクリーム', '120ml×8個入 2,400円(税込)', '1006.jpg', 'こだわりアイスセット8ヶ入（だだちゃ豆・ラ・フランス・胡麻アイス）こころづくし山形だだちゃ・は、鶴岡の人々から頑固なまでに守られ、属まれた独特の香りと深みのある甘さを持った枝・の王様です。半月程度の短い夏の旬の味覚を、心を込めてアイスクリームにしました。', 'ＪＡ鶴岡', '山形県鶴岡市大字覚岸寺字水上199', '0235-29-2828') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1007', '栗饅頭', '1個 140円', '1007.jpg', '店の前にできる行列が目印。1日5000個は売れるという名物の栗饅頭は、しっとりとした薄皮に、ほんのり甘い白あんとホクホクの大栗が入った一品。手みやげとしてもおすすめ。', 'ひと本石田屋', '東京都板橋区上板橋2-32-16', '03-3933-3305') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1008', '辛子明太子伝統', '1箱/360g入　5250円', '1008.jpg', '｢新･食わず嫌い王決定戦｣で紹介されました！TV放映記念★期間限定送料無料!!【TV放映記念...血筋の少ない選び抜かれた原卵を使用し、やまや独自の匠のたれに漬け込んで、168時間熟成させた”明太子を極めた明太子”「伝統シリーズ」です。', 'やまや', '福岡県福岡市東区松島5-27-5', '0120-15-7102') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1009', 'クレーム･オタル', '1箱 3ケ入り　1260円', '1009.jpg', 'フランス、アンジェ地方の家庭菓子「クレーム･ダンジェ」を北海道小樽の新鮮なフロマージュブラン(生チーズ)と生クリームにメレンゲを混ぜ合わせ、素材そのままの風味を生かした一品に仕上げました。デザートソーズは千歳空港近郊で採れるハスカップをふんだんに使用しております。純白のフロマージュブランの舌にとろける優雅な風味に真っ赤なハスカップソースの酸味が絶妙のコントラストを奏でます。ぜひ一度、フワフワの天使の口どけを味わってみて下さい。', 'フランス菓子パリ16区', '北海道札幌市中央区南9条西10−1−18', '0123−24−00') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1010', '醤油赤飯', '不明', '1010.jpg', '', '三京屋', '新潟県三条市仲之町6-15', '0256-32-3608') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1011', '自家製柚子明太子', '（中１箱）　400g　3,675円', '1011.jpg', 'カボチャの味がほんのりするさっぱりしていてとても美味しいお味。カラメルソースも少し苦味があり、ちょっと大人のプリンです。', '相撲茶屋大塚', '福岡県福岡市中央区高砂１丁目19-3', '092-531-9100') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1012', '天然酵母のクロワッサン', '(左)きなこ：170円 (中) (右)チョコレート：180円', '1012.jpg', '(中)プレーン:150円(右)チョコレート:180円添加物を一切使わずに天然酵母100％で作られたクロワッサンは、ずっしりと重量感があり、表面はパリッと中はモッチリの新食感。低温長時間発酵により、発酵過程で旨味成分が形成されます。', '三日月屋', '東京都渋谷区恵比寿4-9-5', '03-5420-2929') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1013', 'マウントバーム しっかり芽', '1ホール(5山)　7875円', '1013.jpg', '1カット（1本）735円から。バームクーヘンの源流であるヨーロッパでも作ることのできない、日本ならではの独特の感性と味覚、菓子職人の技術にもとづいたバームクーヘンの世界を味わい・デザイン・店舗にいたるまで、お客様にご満足いただけるよう、独自につくりあげたバームクーヘン専門店です。「マウントバームしっかり芽」は通常のバームクーヘンの倍近い時間をかけてじっくりと焼き上げた、外はさくっと香ばしく中はしっとりとリッチな味わいです。', 'ねんりん家', '東京都豊島区西池袋1−1−25東武百貨店池袋店地下1階', '03-3316-2356') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1014', 'HommeSweetsハーブキャンディー', '12個入り 1円', '1014.jpg', '飴職人の技が薬草としても知られる西洋ハーブと日本古来の飴を融合させ、現代人の為の精神補助食品として誕生致しました。この『HommeSweets』は、心身の健康にこだわった大人のための飴です。体によい酵素糖と昔から薬効を知られているハーブ＆スパイスそのままの絶妙な組み合わせから生まれた新しい形の精神補助食品、アロマテラピースウィーツです。※人工着色料、人工香味料使用しておりません。', 'レイジースーザン青山店', '東京都港区北青山3-3-11', '03-3403-9546') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1015', 'シュバイツ', '1ホール　1365円', '1015.jpg', 'アーモンド風味のタルトに、砂糖・卵白を加えたマカロンのアーモンドスライスを敷き詰め、二層焼きにしたタルトアマンディーヌ･･･シンプルですが手間をかけ作り上げた逸品です。ぜひ暖めてお召し上がり下さい。br>', 'ドエル', '大阪府茨木市中総持寺町441', '07263284618') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1016', 'まろづけ', '各525円', '1016.jpg', 'ろばた漬けで有名な日光にある檜山昌一商店で特別に袋詰めを行いました。国産の野菜を使用し、保存料・着色料は使用しておりません。＜だいこん＞栃木産のだいこんを秘伝のたまり醤油に漬け込み風味豊かに仕上げました。もろみの香りと旨味。パリパリとした食感が最高です。1ミリ程に薄く切ってお召し上がり下さい。＜しょうが＞高知四万十産のしょうがを秘伝のたまり醤油に漬け込み風味豊かに仕上げました。日本一きれいな四国四万十川の近隣で、育てたものです。筋っぽさのない、やわらかな品で、芳香と辛味が身上です。＜ワインらっきょう＞国内産の甘口らっきょうを赤ワインに漬け込み風味豊かに仕上げました。カリカリ、シャリシャリ、おいしい！いつものこの味この歯ざわり。食べ始めたら、話もはずみます。', '綾小路きみまろオフィシャルショップるりびょうたん', '山梨県南都留郡富士河口湖町河口2720-5', '0555-76-8170') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1017', 'ちまきすし', '1人前8本入　1680円', '1017.jpg', ' ※車えび、厚焼き玉子、いくら、白身魚、サバ、あなご、鮭、蟹の8種のちまきです。', 'すし善蕾亭', '北海道札幌市中央区北一条西275916', '011-614-1177') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1018', 'ミルクフランス', '168円', '1018.jpg', 'ミルク風味のフランスパン生地にコンデンスミルクとバターで作ったクリームを絞ったおやつパン。', 'ラ･ブランジェ･ナイーフ', '東京都目黒区青葉台1-28-7-103', '03-3713-0201') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1019', 'よ志田焼餃子', '6個　290円', '1019.jpg', '「赤坂よ志多」1番人気！焼き餃子10人前総州古白鶏をはじめ新鮮な食材のみを厳選して一つ一つ手作りで仕込んでおります。ニンニク、ニラなど使用しておりませんのでにおいも気にならず、特製のタレにすだちを絞ってヘルシーな餃子を味わってください。皮には、北海道産100％の上質な小麦粉のみを使用しております。', '赤坂よ志田', '東京都港区赤坂2−14−12高橋ビル1階', '03-3583-5046') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1020', '長命寺桜もち', '長命寺桜もち  180円', '1020.jpg', ' 6個入り/1200（箱詰）10個入り/2000（箱詰）12個入り/2300（箱詰，自宅用）12個入り/2700（化粧箱詰，お使い用）通常見る桜餅は餅1個に対して桜の葉1枚であるが当店のは、２、３枚を使用している。', '長命寺桜もち', '東京都墨田区向島5-1-14', '03-3622-3266') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1021', '甘納豆入赤飯', '不明', '1021.jpg', '', '市原調理部', '北海道富良野市若松町3-2', '0167-22-2343') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1022', '太陽の味元気', '500ml　840円 ', '1022.jpg', '太陽の味トマトジュースまるでフルーツジュースのような甘み。北海道下川町の約31件の契約農家さんが、化学肥料を一切使わず有機質肥料で育てあげた心のこもった完熟トマト。自然の美味しさを大切に、トマト本来の味をそのまま閉じ込めたようなトマトジュースです。', '北海道トマトジュース販売', '東京都目黒区下目黒2-9-24', '0120-59-1041') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1023', '黒米おにぎり', '不明', '1023.jpg', '', '愛米家本舗', '東京都目黒区中央町1-3-8', '03-3712-7025') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1024', '黒米おにぎり', '不明', '1024.jpg', '', 'TANTOTANTOELEGANTE', '東京都中央区銀座5-8-17ワールドタウンビル3F', '03-5537-1312') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1025', 'エダムチーズケーキ', '1個　150円', '1025.jpg', '', 'モロゾフ飯田橋ショップ', '東京都新宿区神楽河岸1−1', '078−822−5533') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1026', 'ふらの牛乳プリン', '263円 ', '1026.jpg', ' ふらの牛乳プリン６本セット1,680円（税込・送料別）牛乳瓶のまま焼き上げる事でとても柔らかい食感に仕上がりました。ふらの牛乳、北海道の新鮮な卵、北海道産のお砂糖、バニラビーンズから出来ていますがそれらの素材をそのまま感じらるような優しい仕上りになりました。', 'フラノデリス', '北海道富良野市下御料2156-1', '0167-22-8005') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1027', '梅しそキムカツ', '1480円 ', '1027.jpg', '｢サクッとしてジューシー」厳選された超薄切りの豚ロースを重ねて揚げた、柔らかくて肉汁たっぷりな【キムカツ】今までにない食感とバラエティ豊かな6種類のフレーバーを、是非ご賞味下さい。梅としその香りが豚肉の旨みをひきたてます。 *ぷれーん*黒胡麻*ガーリック*ちーず*ねぎ*梅・しそ', 'キムカツ', '東京都渋谷区恵比寿4-9-5', '03-5420-2929') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1028', 'くるみだれそば', '880円', '1028.jpg', 'くるみに味噌・砂糖などで味付けしたタレでいただく”ざるそば”です。', 'そば工房林檎舎', '長野県北安曇郡白馬村北城八方5289', '0261-71-1566') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1029', '中居くんお気に入りのかすてら', 'プレーン（大）2877円', '1029.jpg', 'カステラの概念が変わる、深く、濃厚な味わい。【金澤烏鶏庵】烏骨鶏かすていらプレーン（大）本品は、なかなか生まれない希少な天来烏骨鶏卵をふんだんに使って、職人が1本1本丁寧に焼いております。天来烏骨鶏卵の深い味わいを生かすために、甘味を抑えしっとりと仕上げました。お菓子の街金沢で生まれた逸品を是非ご堪能ください。', '金澤烏鶏庵', '石川県金沢市西念4丁目22', '0120-367-054') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1030', 'いちごの微笑', 'いちごの微笑（5000円) 25粒入×2カゴ', '1030.jpg', ')25粒入 【送料無料！】産地直送便お取り寄せグルメ京都レマン館いちごの微笑（5000円) 25粒入×2カゴ特製シロップにつけこんだ苺の中にとろーりまろやかな練乳アイスを入れました。優しいいちごの酸味と練乳の甘みがお口の中でハーモニーを奏でます。大人気商品。', 'レマン舘本店（京都円町）', '京都市中京区西ノ京南円町83', '075-841-4144') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone, isEnabled) VALUES('1000', '無効ギフト', '無効', '無効', '無効', '無効', '無効', '無効', 'false') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone) VALUES('1031', '無効レコメンダー', '無効', '無効', '無効', '無効', '無効', '無効') ON CONFLICT DO NOTHING;
INSERT INTO gifts(recommenderId, giftName, price, image, description, shop, address, phone, isEnabled) VALUES('1031', '無効ギフト無効レコメンダー', '無効', '無効', '無効', '無効', '無効', '無効', 'false') ON CONFLICT DO NOTHING;

INSERT INTO favorites(userId, giftId) VALUES('1', '1000') ON CONFLICT DO NOTHING;
INSERT INTO favorites(userId, giftId) VALUES('1', '1001') ON CONFLICT DO NOTHING;
INSERT INTO favorites(userId, giftId) VALUES('2', '1031') ON CONFLICT DO NOTHING;
INSERT INTO favorites(userId, giftId) VALUES('2', '1032') ON CONFLICT DO NOTHING;
INSERT INTO favorites(userId, giftId) VALUES('2', '1033') ON CONFLICT DO NOTHING;
INSERT INTO favorites(userId, giftId) VALUES('3', '1000') ON CONFLICT DO NOTHING;
INSERT INTO favorites(userId, giftId) VALUES('3', '1031') ON CONFLICT DO NOTHING;
INSERT INTO favorites(userId, giftId) VALUES('3', '1032') ON CONFLICT DO NOTHING;
INSERT INTO favorites(userId, giftId) VALUES('3', '1033') ON CONFLICT DO NOTHING;
